import {
  Phone,
  MessageCircle,
  Video,
  Clock,
  Pill,
  CheckCircle,
  XCircle,
  Plus,
  AlertCircle,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Target,
  Award,
  Users,
  Activity,
  Zap,
  Heart,
  Star,
  Trophy,
  Lightbulb,
  X,
  CalendarPlus,
  BarChart2,
  PanelLeft,
  Check,
  ChevronDown,
  ChevronUp,
  Home,
  Bell,
  Search,
  LayoutDashboard,
  CalendarDays,
  Sun,
  Moon
} from "lucide-react"

export const Icons = {
  phone: Phone,
  messageCircle: MessageCircle,
  video: Video,
  clock: Clock,
  pill: Pill,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  plus: Plus,
  alertCircle: AlertCircle,
  calendar: Calendar,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  cloud: Cloud,
  target: Target,
  award: Award,
  users: Users,
  activity: Activity,
  zap: Zap,
  heart: Heart,
  star: Star,
  trophy: Trophy,
  lightbulb: Lightbulb,
  x: X,
  calendarPlus: CalendarPlus,
  barChart2: BarChart2,
  panelLeft: PanelLeft,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  home: Home,
  bell: Bell,
  search: Search,
  layoutDashboard: LayoutDashboard,
  calendarDays: CalendarDays,
  sun: Sun,
  moon: Moon
} 